# PocketPilot relaxed analyzer settings
# (simplified version to reduce warnings)

analyzer:
  errors:
    unused_import: ignore
    unused_local_variable: ignore
    prefer_const_constructors: ignore
    prefer_final_fields: ignore
    unnecessary_this: ignore
    prefer_const_declarations: ignore

linter:
  rules:
    # You can enable individual rules you care about here
    avoid_print: false
